name: Deploy Azure Infrastructure

on:
  workflow_dispatch:

env:
  AZURE_RESOURCE_GROUP: demo-resource-group
  LOCATION: eastasia

  PLAN_NAME: demo-appservice-plan
  WEBAPP1_NAME: demo-webapp-1
  WEBAPP2_NAME: demo-webapp-2
  WEBAPP3_NAME: demo-webapp-3

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Resource Group
        run: |
          az group create \
            --name $AZURE_RESOURCE_GROUP \
            --location $LOCATION

      - name: Create App Service Plan (Linux, B1 SKU)
        run: |
          az appservice plan create \
            --name $PLAN_NAME \
            --resource-group $AZURE_RESOURCE_GROUP \
            --is-linux \
            --sku B1

      - name: Verify Plan Exists
        run: |
          echo "Checking if App Service Plan exists..."
          az appservice plan show \
            --name $PLAN_NAME \
            --resource-group $AZURE_RESOURCE_GROUP

      - name: Create Web App 1
        run: |
          az webapp create \
            --resource-group $AZURE_RESOURCE_GROUP \
            --plan $PLAN_NAME \
            --name $WEBAPP1_NAME \
            --deployment-container-image-name nginx:latest

      - name: Create Web App 2
        run: |
          az webapp create \
            --resource-group $AZURE_RESOURCE_GROUP \
            --plan $PLAN_NAME \
            --name $WEBAPP2_NAME \
            --deployment-container-image-name nginx:latest

      - name: Create Web App 3
        run: |
          az webapp create \
            --resource-group $AZURE_RESOURCE_GROUP \
            --plan $PLAN_NAME \
            --name $WEBAPP3_NAME \
            --deployment-container-image-name nginx:latest
